### ISSUE TITLE
Not running after new commit.

### ISSUE THREAD

**Issue by FrZ-BR** [lonelytb/PUBG-Radar#3]
Others version runned with no problem

![screenshot_3](https://user-images.githubusercontent.com/17305867/36948061-ac552b52-1fb3-11e8-8907-462fcd9bee2e.jpg)

**Comment by lonelytb** [comment]
Try the new version: https://github.com/lonelytb/Radar-Unknown

**Comment by TNning** [comment]
Hello: How to achieve this window, there is a problem coordinates do not follow
https://user-images.githubusercontent.com/35453808/36950830-98ffe8f2-2036-11e8-9e00-6d85ccce3a0c.png
